spring.application.name=correo-central

# Est\u00e1ndar Cl\u00e1sico (Spring Boot 2.x / 3.x)
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:correo_central}

# Est\u00e1ndar Moderno y Streamlined (Spring Boot strict versions)
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:correo_central}

spring.jackson.default-property-inclusion=non_null